stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Building the Docker image..."
    - docker-compose -f docker-compose.yml build

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Deploying the Docker containers..."
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
